### ISSUE TITLE
Gradle task fetchAndUpdateFigmaFiles fails on integration tests

### ISSUE THREAD

**Issue by rylin8** [google/automotive-design-compose#1028]
When running `./gradlew fetchAndUpdateFigmaFiles` after making a breaking change to the serialized document format, the task fails because the integration tests on `Interaction`, `VariantProperties` and `VariantAnimation` fail. This may be because the tests are run on the old version of the .dcf file instead of run after fetching new ones.

In addition, it would be great if this task could also update:
- Design Switcher .dcf file
- Hello World .dcf file
- Tutorial .dcf file (fetch the welcome one, then rename).

This would make it much easier to update all .dcf files, as I currently have to manually update these 6 files before running the task.

Error example:
```
com.android.designcompose.testapp.validation.AnimationMidpoints > variantAnimation FAILED
    java.lang.AssertionError: Failed to assert the following: (DocRenderStatus = 'Rendered')
    Can't retrieve node at index '0' of 'DocClass = 'com.android.designcompose.testapp.validation.examples.VariantAnimationTestGen''
    There are no existing nodes for that selector.
        at androidx.compose.ui.test.SemanticsNodeInteraction.fetchOneOrDie(SemanticsNodeInteraction.kt:175)
        at androidx.compose.ui.test.SemanticsNodeInteraction.fetchOneOrDie$default(SemanticsNodeInteraction.kt:150)
        at androidx.compose.ui.test.SemanticsNodeInteraction.fetchSemanticsNode(SemanticsNodeInteraction.kt:84)
        at androidx.compose.ui.test.AssertionsKt.assert(Assertions.kt:263)
        at androidx.compose.ui.test.AssertionsKt.assert$default(Assertions.kt:255)
        at com.android.designcompose.test.InstrumentedTestUtilsKt.assertRenderStatus(InstrumentedTestUtils.kt:31)
        at com.android.designcompose.testapp.validation.AnimationMidpoints.variantAnimation(AnimationMidpoints.kt:74)

```

**Comment by timothyfroehlich** [comment]
Assigning to Ralph for priority

**Comment by yiqunw700** [comment]
Closing this ticket with #1611 and #1804 merged. Hello world and tutorial apps can be fetched manually using the scripts.
