### ISSUE TITLE
Linear gradients are missing all color stops and causing a crash

### ISSUE THREAD

**Issue by iamralpht** [google/automotive-design-compose#1035]
Via @Heneveld, [a recent regression in the Figma API](https://forum.figma.com/t/can-not-get-color-of-gradient-linear-by-rest-api/70415), causes a crash in DesignCompose:

```
java.lang.IllegalArgumentException: needs >= 2 number of colors
at android.graphics.Shader.convertColors(Shader.java:190)
at android.graphics.LinearGradient.<init>(LinearGradient.java:70)
at androidx.compose.ui.graphics.AndroidShader_androidKt.ActualLinearGradientShader-VjE6UOU(AndroidShader.android.kt:39)
at androidx.compose.ui.graphics.ShaderKt.LinearGradientShader-VjE6UOU(Shader.kt:44)
at com.android.designcompose.RelativeLinearGradient.createShader-uvyYCjk(Utils.kt:815)
at androidx.compose.ui.graphics.ShaderBrush.applyTo-Pq9zytI(Brush.kt:661)
at com.android.designcompose.FrameRenderKt.render(FrameRender.kt:365)
``` 

We should not crash in this case. Either we validate that there are at least two stops in the Figma API to DCF conversion (and log if not, discarding the fill), OR we do it in Kotlin (e.g. `ShaderBrush.applyTo`), OR both.

**Comment by rylin8** [comment]
The Kotlin code that creates a brush from the color stops is here https://github.com/google/automotive-design-compose/blob/0552d72a4970346782f7766f9dd7d4dab3b6790d/designcompose/src/main/java/com/android/designcompose/Utils.kt#L1234

**Comment by iamralpht** [comment]
Probably wise to do the same check for the other gradient types, too, and log & return `Background::None` in Rust, and log & return `null` in the Kotlin shader brush util.
