### ISSUE TITLE
Interaction overlay position test crashed when I clicked on the `M` button twice

### ISSUE THREAD

**Issue by yiqunw700** [google/automotive-design-compose#1698]
Repo steps:
1. Squoosh on
2. Navigate to the `Interaction` test -> `Overlay Position`
3. Click `M` button for the `Manual` position twice.
4. App crashed.
```
2024-10-03 15:30:48.456 18883-18883 DC_SQUOOSH              com...igncompose.testapp.validation  E  Duplicate layout ID: 229; cannot proceed...
2024-10-03 15:30:48.474 18883-18883 AndroidRuntime          com...igncompose.testapp.validation  E  FATAL EXCEPTION: main (Ask Gemini)
                                                                                                    Process: com.android.designcompose.testapp.validation, PID: 18883
                                                                                                    java.lang.RuntimeException: Duplicate layout ID: 229
                                                                                                    	at com.android.designcompose.squoosh.SquooshLayoutIdAllocator.visitLayoutId(SquooshLayout.kt:105)
                                                                                                    	at com.android.designcompose.squoosh.SquooshTreeBuilderKt.resolveVariantsRecursively(SquooshTreeBuilder.kt:243)
                                                                                                    	at com.android.designcompose.squoosh.SquooshTreeBuilderKt.resolveVariantsRecursively$default(SquooshTreeBuilder.kt:129)
                                                                                                    	at com.android.designcompose.squoosh.SquooshTreeBuilderKt.resolveVariantsRecursively(SquooshTreeBuilder.kt:390)
                                                                                                    	at com.android.designcompose.squoosh.SquooshTreeBuilderKt.resolveVariantsRecursively$default(SquooshTreeBuilder.kt:129)
                                                                                                    	at com.android.designcompose.squoosh.SquooshRootKt.SquooshRoot(SquooshRoot.kt:314)
                                                                                                    	at com.android.designcompose.squoosh.SquooshRootKt$SquooshRoot$8.invoke(Unknown Source:31)
                                                                                                    	at com.android.designcompose.squoosh.SquooshRootKt$SquooshRoot$8.invoke(Unknown Source:10)
                                                                                                    	at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:192)
                                                                                                    	at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2825)
                                                                                                    	at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:3116)
                                                                                                    	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3607)
                                                                                                    	at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(Composer.kt:3552)
                                                                                                    	at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:948)
                                                                                                    	at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:1206)
                                                                                                    	at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:132)
                                                                                                    	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:616)
                                                                                                    	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:585)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:41)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1035)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:845)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:775)
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7870)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
                                                                                                    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.runtime.PausableMonotonicFrameClock@6c622c3, androidx.compose.ui.platform.MotionDurationScaleImpl@6c66740, StandaloneCoroutine{Cancelling}@16fa679, AndroidUiDispatcher@bd8efbe]
```

This might be similar to #1605

**Comment by rylin8** [comment]
This was fixed with https://github.com/google/automotive-design-compose/pull/2018
